language: csharp

sudo: false  # use the new container-based Travis infrastructure

script: 
  - cd CSharp/
  - ./build.sh Default
  - cd ..

branches:
  except:
    - gh-pages

before_install:
 - chmod +x build.sh
 - chmod +x CSharp/build.sh