language: csharp

sudo: false  # use the new container-based Travis infrastructure

script: 
  - ./CSharp/build.sh Default

branches:
  except:
    - gh-pages

before_install:
 - chmod +x build.sh
 - chmod +x CSharp/build.sh