language: csharp

sudo: false  # use the new container-based Travis infrastructure

script: 
  - cd CSharp/
  - ./build.sh BuildApp
  - cd ..
  - cd FSharp/
  - ./build.sh BuildApp
  - cd ..

branches:
  except:
    - gh-pages

before_install:
 - chmod +x CSharp/build.sh
 - chmod +x FSharp/build.sh